### ISSUE TITLE
Queries don't work for strings with non ascii characters (acute accent, cedilla, unicode…)

### ISSUE THREAD

**Issue by pyrog** [tyrasd/overpass-turbo#126]
*  ```fountain in Besançon``` display an error message, but ```fountain in Besancon``` work fine
* ```"bus stop" around Béziers``` don't work, the "good" query is ```"bus stop" around Beziers```

**Comment by tyrasd** [comment]
I think overall this is a really good usability improvement. :+1: And thanks for the pull request.

**Comment by pyrog** [comment]
Thanks Martin :smile: 

But did you use my PR ?, there is still this an issue (an maybe a new one):
* ```railway=station in 昌平北```<br/>The wizard don't accept this syntax
* ```railway=station in '昌平北'``` or  ```railway=station in "昌平北"```<br/>Nominatim can't find this name.

If I query directly Nominatim, this station is founded:
* [昌平北](http://nominatim.openstreetmap.org/search.php?q=%E6%98%8C%E5%B9%B3%E5%8C%97)
* [Changping North](http://nominatim.openstreetmap.org/search.php?q=Changping+North)

**Comment by tyrasd** [comment]
> is my PR online?

Not [yet](https://github.com/tyrasd/overpass-turbo/blob/master/CHANGELOG.md). But there is a beta instance at http://overpass-turbo.eu/master/

Your example doesn't work because [`昌平北`](http://overpass-turbo.eu/master/?Q=%2F*%0AThis%20has%20been%20generated%20by%20the%20overpass-turbo%20wizard.%0AThe%20original%20search%20was%3A%0A%E2%80%9Cname%3D%E6%98%8C%E5%B9%B3%E5%8C%97%20global%E2%80%9D%0A*%2F%0A%5Bout%3Ajson%5D%5Btimeout%3A25%5D%3B%0A%2F%2F%20gather%20results%0A(%0A%20%20%2F%2F%20query%20part%20for%3A%20%E2%80%9Cname%3D%22%E6%98%8C%E5%B9%B3%E5%8C%97%22%E2%80%9D%0A%20%20node%5B%22name%22%3D%22%E6%98%8C%E5%B9%B3%E5%8C%97%22%5D%3B%0A%20%20way%5B%22name%22%3D%22%E6%98%8C%E5%B9%B3%E5%8C%97%22%5D%3B%0A%20%20relation%5B%22name%22%3D%22%E6%98%8C%E5%B9%B3%E5%8C%97%22%5D%3B%0A)%3B%0A%2F%2F%20print%20results%0Aout%20body%3B%0A%3E%3B%0Aout%20skel%20qt%3B&C=40.22952;116.22718;18&R) is already the name of a particular railway station (mapped as a node) and not an *area* to search stuff *in*. Searching in the surrounding administrative area works like expected: [`railway=station in 昌平区`](http://overpass-turbo.eu/master/?w=railway=station%20in%20%E6%98%8C%E5%B9%B3%E5%8C%BA&R) (as does searching around the original one [`railway=station around 昌平北`](http://overpass-turbo.eu/master/?w=railway=station%20around%20%E6%98%8C%E5%B9%B3%E5%8C%97&R)).

**Comment by pyrog** [comment]
> Your example doesn't work because [this is] the name of a [node] and not an area to search stuff in. 

Ok, I understand :smile:  I see the filter pass to the Nominatim search in [js/ide.js#L824](https://github.com/tyrasd/overpass-turbo/blob/b0ef5ebbdd353c1bc7e45da527cab03498b4cbef/js/ide.js#L824):
 ```javascript
    function filter(n) {
      return n.osm_type && n.osm_id && n.osm_type!=="node";
    } 
 ```

The *"issue"* is that the error message is not clear: <br/>`Nominatim Error -  Could not find anything with the following name`

In fact, Nominatim find this place but Overpass turbo reject it because it's a node:
Could you:
* remove the filter and display a specific error message?<br/>
`Could not find anything within a node object`

or best?

* replace the `… in placename` by `… around placename` for nodes ?<br/>
[railway=station in 昌平北](http://overpass-turbo.eu/master/?q=LyoKVGhpcyBoYcSGYmVlbiBnxI1lcmF0ZWQgYnkgdGhlIG92xJJwxIlzLXR1cmJvIHdpemFyZC7EgsSdxJ9yaWdpbmFsIHNlxLBjaMSsxIk6CsOiwoDCnMSTaWx3YXk9c3TElGlvxI7EuiDDpsKYwozDpcK5wrPDpcKMwpfFiMKdCiovCltvdXQ6anPFll1bdGltZcWqxawyNV07Ci8vIGZldMWCIMSwxYAgxYjCnMSjxLdzxaPEm8SrxL_FgcWDxLoKe3vEkG9jb2RlQXLFgDrFmsWcxZ7FoMKXfX0tPi7GkXLFgsaexYDFvMW-xI_ElMSdciDGn3N1bHRzCigKICDGsnF1xJLEmsaLdMaAb3I6xojFicWLxY3Fj8WRxZPFs8WWxaPHgCBuxptlWyLHkMWOeSI9IsWSxZTFliJdKMaGYcarxYDGrWjGr2EpxbzHgcegx53Hn8WPx6LHpMeUxZVux6jHqsafx6zGrMauyIHHs8eYxp9sx6Zux7dhxYzHoMe6x6XHlce-x6nHq8etxpLHsciGyIbGsnDEt27Hica4xrrGvArFt8SYxpt5xbw-xbzIpHNrZcS9cXQ7&c=B5PN1qsePS) :arrow_right: [railway=station around 昌平北](http://overpass-turbo.eu/master/?q=LyoKVGhpcyBoYcSGYmVlbiBnxI1lcmF0ZWQgYnkgdGhlIG92xJJwxIlzLXR1cmJvIHdpemFyZC7EgsSdxJ9yaWdpbmFsIHNlxLBjaMSsxIk6CsOiwoDCnCDEk2lsd2F5PXN0xJRpb8SOxLBvdW7El8OmwpjCjMOlwrnCs8OlwozCl8WIwp0KKi8KW8WadDpqc8WXXVt0aW1lxa46MjVdOwovLyBhZGp1xZPEm8S1xL_FgcWDxJNkacaHICjEuiDFuMSVcnMpxIfEkmUKe3vGjsaQcz0xMMamfX3GgMaCZ8SUxJ1yxYtlc3VsdHMKKAogIMaBIHF1xJLEmsSjcnQgZm9yOiDFiMKcxYzFjsWQxZLFlMW2xZfFp8a5IG5vZGVbIseNxY95Ij0ixZPFlcWXIl0oxZnFm2Q6xp_GocaHxqgsxp_EkG9jx5hlQ2_Hh2RzOsWexaDFosWkwpfGqCnFv8a6x57Hm8edxZDHoMeix5HFlm7HpseocsWaxZzHrMagxoTGosewx7LFuce1x5nHuMe6x7zHvsWhxaPFpciDyIXGsGzHpG7IiGHFjceeyIvHo8eSyI_Hp8epyJTHrciXx699x7F7x7PInMe3x7nEscigxZ_IosiByKUKyITGqiBwxLdux4RyxrHGs8a1CsWuxJjHmHnFvz7Fv8mTc2tlxL1xdDs&c=B5PNXoFmQS)

**Comment by tyrasd** [comment]
Your second proposal sounds good, maybe together with a more verbose message why the *in* query doesn't work. But as this is doesn't have much to do with the original topic in this ticket, I'm going to open a new one for it.
