### ISSUE TITLE
export to JOSM fails in latest (unstable) versions of JOSM

### ISSUE THREAD

**Issue by brycenesbitt** [tyrasd/overpass-turbo#158]
With current overpass and JOSM Version 8243, JOSM gives:

Cannot open URL 'http://overpass-api.de/api/interpreter?fixme=JOSM-ticket-8566&data=%2F*%0AThis%20has....' The following download tasks accept the URL patterns shown:

Due to the fixme=JOSM-ticket-8566 string.

**Comment by tyrasd** [comment]
Damn it. This used to work until a few days ago. Here is the link to the original [josm-ticket](http://josm.openstreetmap.de/ticket/8566) that explains why this workaround is necessary.

@simon04: do you have an idea what changed between JOSM 8159 and now that makes this workaround fail?

**Comment by mmd-osm** [comment]
Testing revisions:
8200 affected by this issue
8190 not affected
8195 not affected
8198 affected
8196 not affected
8197 affected  <<<--- first bad commit

**Comment by tyrasd** [comment]
Here is the source code of [commit 8197](http://josm.openstreetmap.de/changeset/8197/josm).

**Comment by brycenesbitt** [comment]
FYI: here's how that code works:

There are multiple download tasks.
Each can handle certain URL patterns.
The dialog shows all those patterns.


Other download strings, including XAPI, continue to work.

**Comment by tyrasd** [comment]
Yes, but this used to be the case even before the above mentioned commit. The workaround (`fixme=JOSM-ticket-8566`) in overpass turbo was necessary because the code handling the Overpass URL pattern doesn't properly handle URL-encoded special character (which it should), thus making the export from overpass turbo unusable in those cases. There used to be a fallback mode in JOSM which actually did properly handle the URL-encoded values supplied via remote control, but it appears not to work anymore. :(

**Comment by mmd-osm** [comment]
There's a regex check for permissible Overpass API strings, which doesn't allow the `interpreter?fixme=` workaround. This regex is around for some time already, though I don't know, why this suddenly kicked in with revision 8197.

**Comment by tyrasd** [comment]
Sure. The `fixme…` part was explicitly added to the URL such that the regex *doesn't* kick in.

**Comment by simon04** [comment]
Fixed, see https://josm.openstreetmap.de/ticket/11356 and https://josm.openstreetmap.de/changeset/8249/josm

I do not get what the `fixme=JOSM-ticket-8566` is for. Without this it would have worked with r8197.

**Comment by tyrasd** [comment]
Thank you very much for the quick reaction, Simon.

Also, I'd like to apologize as I was mistaken in that the ugly `fixme=…` workaround is still needed. It isn't. I believe I kept it in because at the time when the original bug was fixed, many still used slightly outdated versions of JOSM. And then I simply didn't look into that part of the code anymore, and yesterday I just assumed that it is still relevant without doublechecking. **Sorry for that and sorry for the noise!**

**Comment by brycenesbitt** [comment]
I just rebuilt JOSM from SVN, and while the error dialog is gone, no data is loaded.

**Comment by simon04** [comment]
Are you accidentally loading JSON data? That's what I accidentally did while testing …

**Comment by brycenesbitt** [comment]
It's working now.
