### ISSUE TITLE
Autorepair for edit in JSOM feature does not work in all cases

### ISSUE THREAD

**Issue by saerdnaer** [tyrasd/overpass-turbo#177]
When I try to use the `Export` -> `Edit in JOSM` link with following example query, the autorepair feature doesn't recoginize it has to replace the `[out:json]` with `[out:xml]`. 

http://overpass-turbo.eu/s/agh
```
[out:json];
{{geocodeArea:Vienna}};
node["tourism"="museum"](area);
out meta;
```
When I remove the `meta` everything works as expected.  

(This issue came up during the FOSSGIS Hacking Event last WE)

**Comment by mmd-osm** [comment]
In the shortlink, the first line looks a bit different:

```C
[out:json][timeout:25];
```

Issue:  Regexp for [out:xxx] expects a semicolon at the end (see https://github.com/tyrasd/overpass-turbo/blob/master/js/autorepair.js#L178)

`[out:josn][timeout:25];` doesn't have that semicolon, so that  err.output = true; will not be set.

When you remove `meta`, you trigger another error situation (err.meta=true;) so that the query repair kicks in.

Maybe removing that last `;` in the regex would be ok to fix this?

```Javascript
    var out = q.match(/\[\s*out\s*:\s*([^\]\s]+)\s*\]\s*;/);
```
