### ISSUE TITLE
Weird error message

### ISSUE THREAD

**Issue by k1wiosm** [tyrasd/overpass-turbo#203]
I keep getting this error message: 

    An error occured during the execution of the overpass query!
    
    Request rejected. (e.g. server not found, request blocked by browser addon, request redirected, internal server errors, etc.)
    
    Error-Code: error (0)

with this query:

    [out:json][timeout:300][date:"2015-09-01T00:00:00Z"];
    {{geocodeArea:USA}}->.searchArea;
    (
      node["exit_to"](area.searchArea);
      way["destination"]["highway"="motorway_link"](area.searchArea);
      way["destination"]["highway"="motorway"](area.searchArea);
    );
    out count;

However using dev server it works:

    {{data:overpass,server=http://dev.overpass-api.de/api_mmd/}}

**Comment by mmd-osm** [comment]
Hi there,

the error message for sure is not related to overpass turbo, but comes directly from Overpass API.

The dev server URL you're using has a custom Overpass beta version running, which includes a number of performance related improvements. None of those ideas have made it yet into the main Overpass API branch, that's why you see different behavior.

Read more about it here: https://github.com/mmd-osm/Overpass-API/wiki/Overpass-API-test754

In general your question would be better suited for the Overpass API repo under https://github.com/drolbr/Overpass-API
