### ISSUE TITLE
Wizard query creation for area with JOSM not working

### ISSUE THREAD

**Issue by malenki** [tyrasd/overpass-turbo#209]
"create query" from "Download via Overpass API" in JOSM contrary to Overpass Turbo cannot handle areas.
When I want to query for "Hotel in Freiberg" I get the response
"The Overpass wizard could not parse the following query: Hotel in Freiberg"
When I use a query created with Overpass Turbo Wizard in "Download via Overpass API" I get the response "OSM-Server »overpass-api.de« reports an erroneous query." 
("Der OSM-Server »overpass-api.de« meldet eine fehlerhafte Anfrage.")

It would be nice to have qerying for an area working in JOSM.

**Comment by tyrasd** [comment]
OK, this is mostly because JOSM's overpass implementation doesn't implement the [extended Overpass query](http://wiki.openstreetmap.org/wiki/Overpass_turbo/Extended_Overpass_Queries) syntax from overpass turbo. So, this ticket would be more appropriate in JOSM's [bug tracker](https://josm.openstreetmap.de/report). //cc @simon04 

Here's a workaround for the time being: construct the query in overpass turbo, hit *Export*, then *Query* and use *Als Text* to get the processed-down version of the query that can be used in JOSM (or any other tool working with raw Overpass API requests).

**Comment by simon04** [comment]
The same issue has already been reported on the JOSM bug tracker: https://josm.openstreetmap.de/ticket/11975
