### ISSUE TITLE
download in JOSM not working

### ISSUE THREAD

**Issue by baditaflorin** [tyrasd/overpass-turbo#236]
I can run the query in the browser, but when i try in JOSM i either get the download it but then i get a empty result, or i get timeout error. 

http://overpass-turbo.eu/s/gf8

**Comment by mmd-osm** [comment]
If your query works in overpass turbo, but not in JOSM, why don't you create a ticket in [JOSM bugtracker](https://josm.openstreetmap.de/newticket) instead?

**Comment by mmd-osm** [comment]
Copy from wiki:

Your request searches in historic diffs; this requires using an Operpass API supporting "attic" data (only the Russian and German instances of Overpass have these data, not the French or Swiss instances)
For now the Russian instance is broken for this kind of search (internal server error when looking into attic data). The German instance also has problems joining object id's from Attic data so you get the 0/0/0 states in "loaded". Also you cannot dowload data in JOSM with only the object ids if these objects have been deleted in theirs most recent version, you will not get the objects you were finding in Attic, or not the same geoemtry/tags, that's hy you can't find anything when downloading into JOSM (this would require downloading old versions and to use the "restore" plugin). All these 265 lines are found but not the nodes they were defined with because lines do not specify which node version they used and all the nodes were deleted. Overpass API does not currently manage well the attic data. View each object you get, and attempt to restore them individually in JOSM, but you'll need to also look for individual node version...
    Note also that your query only searches nodes in the same period of last modification, but they may have been deleted AFTER the deletion of lines and not modified in your search period, so these nodes are not found. I suggest you use a restore addon to retreive all objects with their correct dependant versions (locate the changeset number of the line then look for nodes in the last changeset number before or equal to the changeset number of the line). So your query is not correct for what you are trying to do. — Verdy_p (talk) 15:49, 17 May 2016 (UTC)

**Comment by tyrasd** [comment]
Thanks @mmd-osm for posting the answer from the osm wiki.

In principle, overpass turbo doesn't support (a)diffs returned by the Overpass API at all and the fact that some data is shown in this case is a mere coincidence/bug (resulting from some overly forgiving parsing code). If you'd like to show additions from a particular user you should better use the `[date:…]` filter together with a `(newer:…)` statement, e.g. http://overpass-turbo.eu/s/goM which can be loaded into JOSM for further inspection. Or if you're interested in a visualization of the actually changed data (incl. deletions and before-after modifications), use a specialized tool such as [achavi](http://github.com/nrenner/achavi). @baditaflorin: does this answer your question?
