### ISSUE TITLE
Regex query with pipe

### ISSUE THREAD

**Issue by planemad** [tyrasd/overpass-turbo#239]
Been trying to create a query to find invalid turn lanes to catch:

- `turn:lanes` where the left turn lane comes after an empty turn lane. eg `turn:lanes:forward=|left|`

But there seems to be some issue with using pipes in the query. Using `[~"^turn:lanes.*"~"^|.*left.+"]` seems to ignore the pipe and return all lanes with left http://overpass-turbo.eu/s/goD

Does the pipe `|` need to be escaped somehow? `\|` does not work.

cc @tyrasd

**Comment by mmd-osm** [comment]
See https://github.com/drolbr/Overpass-API/issues/271

**Comment by tyrasd** [comment]
Yes, you need to escape the pipe character, because it has the meaning of "or" in a regex. But as Overpass QL uses the backslash as [it's own](http://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#Value_matches_regular_expression_.28.7E.2C_.21.7E.29) escaping character (e.g. to insert a literal `"` or special unicode characters), you must escape the backslash in order for it to pass through to the actual regex. This should work:

    [~"^turn:lanes.*"~"^\\|.*left.+"]

Note that you can also use the query wizard to help you with escaping special characters: If you do a partial string search in the query wizard (using the `:` operator), the wizard creates a properly escaped regex for the particular term for you.

**Comment by slhh** [comment]
Unfortunately, the wizard doesn't convert a standard regexp to the Operpass-QL format.
I think it should better do so, but at least this special snytax requirement should be mentioned in the documentation of the wizard. The used regexp syntax should be defined anyway because several different standard regexp types do exit.
Due to suppoting pipe as metacharacter it might currently be POSIX extended regular expression syntax, but with every backslash (metacaracter or not) duplicated.

**Comment by tyrasd** [comment]
> Unfortunately, the wizard doesn't convert a standard regexp to the Operpass-QL format.

It does. At least if you're using the "standard" regexp syntax with slashes as delimiters. E.g. `name~/\./` in the wizard creates `["name"~"\\."]` OverpassQL statements. If you're using "string" regexp expressions (as in `name~"\."`) it doesn't work because there the backslash is also used as an escape character.

**Comment by erickdeoliveiraleal** [comment]
I'm trying to use the regex \d{7,}|[5-9](?=\d*[1-9])\d{5} but I keep getting error:

` static error: Invalid regular expression: "\d{7,}|[5-9](?=\d*[1-9])\d{5}"`
