### ISSUE TITLE
Automatically remove bbox at z0-z3

### ISSUE THREAD

**Issue by d1g** [tyrasd/overpass-turbo#272]
There a huge performance penalty when running _almost global queries_ (in contrast to global queries):

[It was suggested to remove bbox part](https://github.com/drolbr/Overpass-API/issues/329#issuecomment-255221249) or to run "one global query & caching the result".

_I don't think that any user would set custom bbox at z0-z3 level._

**Comment by tyrasd** [comment]
You mean that overpass turbo generally remove `({{bbox}})` statements from queries where the bbox is very large? In my opinion, these are optimizations that should be done on the API/server side (i.e.a query scheduler which knows in which order the individual selectors should be applied in order to obtain the most performance), rather than some intransparent magic on the client (e.g. what if actually wants to query data in a large bbox — let's say when someone's looking for something like roads inside an ocean).

**Comment by d1g** [comment]
@tyrasd 
>  these are optimizations that should be done on the API/server side

then server needs this information about "zoom level". _I can see bbox information (4 coords) in POST, but not zoom level._

> roads inside an ocean

bbox at z3 is really [huge](http://overpass-turbo.eu/s/jRN), way bigger than single ocean: _I was able to capture: Africa, Australia, NZ, UK, Indian ocean, 1/2 of the Atlantic ocean, 80% of the Europe and almost all inhabited Asia_

**Comment by tyrasd** [comment]
> I can see bbox information (4 coords) in POST, but not zoom level.

Well, overpass turbo also basically only knows the 4 bbox coordinates (zoom level is irrelevant because one can set a small bbox while being zoomed all the way out; and people have different monitors: on mobile z3 shows a much smaller square than z3 on a 4k monitor), and the bbox is basically the only relevant thing influencing query performance on the server.
