### ISSUE TITLE
Link for images

### ISSUE THREAD

**Issue by Robot8A** [tyrasd/overpass-turbo#281]
![image](https://cloud.githubusercontent.com/assets/19521377/21991605/8dbe6bd4-dc13-11e6-96de-9bbe1826e51b.png)
It would be great for developers to have a link to convert queries to png image.
Thanks in advance!

**Comment by tyrasd** [comment]
I'm not sure if I understand your question. Would you like to have a URL parameter that given an Overpass query (and parameters) produces a png image of the result right away instead of showing the user interface? Can you elaborate this a bit more? What would one use this for?

**Comment by Robot8A** [comment]
Yeah, that is exactly what I want.
I would use it for my Telegram bot, to show the location of nearby bus/tram/bike sharing stops using Overpass.

**Comment by tyrasd** [comment]
Ok, I see. Unfortunately, that's not something that can be easily implemented in overpass turbo, since it doesn't have a server side component that could serve the png output. Currently, the png is generated on the client where a browser environment (DOM, javascript engine, etc.) is required to be present.

I think at least some parts of the overpass turbo code could be reused to build such a service. But it would require some work to get it up and running. And I'm not quite sure that I cannot find time to implement that in the near future. (therefore, I'm closing this issue here)

An alternative approach for your use-case could be to use [query-overpass](https://www.npmjs.com/package/query-overpass#cli) to fetch the data from overpass and convert it to geojson, and then use something like [mapbox' static map api](https://www.mapbox.com/api-documentation/#static-classic) to display that data on a static map.

**Comment by Robot8A** [comment]
Thanks
