### ISSUE TITLE
Missing polygons fully contained in bounding box

### ISSUE THREAD

**Issue by joaquim-rosa** [tyrasd/overpass-turbo#291]
Dear developers,

I'm facing an issue when querying a region that is fully contained in a river, for example.
In that case the query does not return any results, while it should return the polygon of the river where it is contained.

I attach here two pictures. In pic 1 the region is fully contained on the river, and in pic 2 the region is not fully contained. In pic 2 you can see that I receive the polygon I wanted, but in pic 1 nothing is returned.

The coordinates of the bounding box of pic 1 are approximately:
(51.359297,4.290197,51.360933,4.293232)

The coordinates of the bounding box of pic 2 are approximately:
(51.359297,4.290197,51.360933,4.294185)

Have you seen this before? Do you have any suggestion on how to approach this?
Many thanks.

Pic 1:
![pic1](https://cloud.githubusercontent.com/assets/28263737/25583354/ba5784ca-2e91-11e7-94cb-d8408210f42b.png)

Pic 2:
![pic2](https://cloud.githubusercontent.com/assets/28263737/25583355/ba5bac08-2e91-11e7-8c42-1687690b1409.png)

**Comment by tyrasd** [comment]
Hi. This is so by design. Overpass considers all osm ways to be lines and therefore it can't know that the small bounding box is "fully inside" the area defined by the osm way.

As a workaroud, in some cases you may be able to use the [`is_in` statement](http://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#Query_for_areas_.28is_in.29) for this, which returns all "areas" (a subset of osm features that are "known" to define "interesting" areas) that cover a given coordinate point: http://overpass-turbo.eu/s/oNj

**Comment by joaquim-rosa** [comment]
Hi. The is_in statement probably suits my needs. Thanks for your feedback.
