### ISSUE TITLE
Holes in Multipolygons with distinct tags aren't interpreted as polygons anymore

### ISSUE THREAD

**Issue by Weltstaat** [tyrasd/overpass-turbo#315]
Dear developers,

in the past Overpass Turbo would return tagged holes of multipolygons as Geojson Polygons when querying for the multipolygon as well as for the hole. For example, a multipolygon with the tag "public_transport=platform", where the way of the inner relation member has the distinct tag "building:part=elevator" would return two seperate polygons, if querying for both of those tags. Now only one polygon is returned (that of the platform with a hole inside) and a line feature for the boundarys of the elevator. 

See also: http://overpass-turbo.eu/s/paY

Was this change by purpose? Is there a way to still get two polygons?

Thanks.

**Comment by tyrasd** [comment]
Hi. Well, are you sure this case was ever handled "correctly"? The issue is that your output contains way 416161922 twice (once with its own tags and once without tags from the recurse `>`+ `out skel`). This *should* be handled better by the latest versions of osmtogeojson (since https://github.com/tyrasd/osmtogeojson/issues/23), but apparently there's still a bug there. I've opened https://github.com/tyrasd/osmtogeojson/issues/76 for it.

As a workaround: If you change your query to not output any objects twice, it works as expected: for example like so: http://overpass-turbo.eu/s/pb4, but using `out geom;` might be the best solution for this kind of queries anyway: http://overpass-turbo.eu/s/pb5 (regardless of this bug or not).

**Comment by Weltstaat** [comment]
Yes, for some reasons it worked like that about a month ago and numerous times before that.

Well, thank you for the answer! The workaround will satisfy my needs for now.
