### ISSUE TITLE
Allow nested shortcuts

### ISSUE THREAD

**Issue by zstadler** [tyrasd/overpass-turbo#342]
As far as I could see, shortcuts cannot be used within other shortcuts.

For example, this is an attempt to use nested shortcuts for finding leading, trailing and multiple blanks in `name*` tags.

```
// Define a blank character
{{blank=[[:blank:]]}}

// Define a Key/value regular expression for leading, training or multiple blanks
{{cond=[~"^name"~"^{{blank}}|{{blank}}$|{{blank}}{{blank}}"]}}

(
  node     {{cond}}({{bbox}});
  way      {{cond}}({{bbox}});
  relation {{cond}}({{bbox}});
);
out meta geom;
```

Currently, the second shortcut definition is interpreted as a `{{cond=[~"^name"~"^{{blank}}` followed by a syntax error `|{{blank}}$|{{blank}}{{blank}}"]}}`

I would expect the second shortcut definition to be interpreted as
```
{{cond=[~"^name"~"^[[:blank:]]|[[:blank:]]$|[[:blank:]][[:blank:]]"]}}
```

_Edited to comply with POSIX Regular Expression syntax_

**Comment by mmd-osm** [comment]
Hmm, not sure this example really needs nested shortcuts. I would probably use:

```
[bbox:{{bbox}}];
(
  node[~"^name"~"^[ \t]|[ \t]$|[ \t]{2,}"];
  way[~"^name"~"^[ \t]|[ \t]$|[ \t]{2,}"];
  rel[~"^name"~"^[ \t]|[ \t]$|[ \t]{2,}"];
);
out geom;
```

**Comment by zstadler** [comment]
Shortcuts were defined in order to reduce copy-paste, and that's what I'm trying to do.

In other examples, `{{blank}}` would be replaced by `{{EnAr=[a-z؀-ۿݐ-ݿ]}}` and `{{cond}}` would be a different expression using it a few times.

**Comment by tyrasd** [comment]
I see your point, but in my eyes this is a rather special thing which would complicate the current shortcut implementation by a large amount.

Btw: Yes, shortcuts can reduce copy-paste, but they were primarily meant to facilitate de-duplication of varying user input (e.g. when you have a query that can work on arbitrary highway types, you should only have to swap the tag out at a single place in the overpassQL+turbo script rather than in multiple places).
