### ISSUE TITLE
JSON output not formatted correctly for multiple admin units

### ISSUE THREAD

**Issue by SK53** [tyrasd/overpass-turbo#353]
Not seen this before, a query for admin_level=4 on S. Chile and Argentina produces strangely formatted polygons: admin_level=4 (http://overpass-turbo.eu/s/tMI).

When a specific province is requested the polygon is correctly formatted: e.g., admin_level=4 and name=Chubut or [admin_level=4 and "dbachile:id"=11.](http://overpass-turbo.eu/s/tMJ). When several provinces are selected there seems to be something wrong in the ordering of polygon vertices. This seems to be general, for instance townland boundaries in Ireland which certainly used to work: http://overpass-turbo.eu/s/tMK.

**Comment by tyrasd** [comment]
this reminds me of https://github.com/tyrasd/overpass-turbo/issues/182 aka https://github.com/tyrasd/osmtogeojson/issues/38. my first guess would be that the [deduplication](https://github.com/tyrasd/osmtogeojson/issues/23) code still has a bug here…

As a workaround you can replace the output part of your query (everything after the `// print results` comment) to either just `out geom;` (http://overpass-turbo.eu/s/tND) or `(._;>;); out;`. That works as expected.

PS: But are you sure you really want even the nodes and ways with admin_level=4 (http://overpass-turbo.eu/s/tNE) in your output (instead of only the boundary relations: http://overpass-turbo.eu/s/tNF)?

**Comment by SK53** [comment]
Many thanks for the help. It indeed does look like #182. 

Was running a basic wizard query to get some data quickly. Am pretty sure behaviour has changed as I used the Irish Townlands one to check stuff whilst I was mapping it. 

Will close this as there are adequate work-arounds.

**Comment by tyrasd** [comment]
let's keep it open, since it's triggered by the default wizard output. I'd like to take a look at it, and if the issue is closed I might forget it. :see_no_evil:
