### ISSUE TITLE
donations

### ISSUE THREAD

**Issue by riccardoklinger** [tyrasd/overpass-turbo#397]
DO you get financial support from OSM Foundation? I am maintaining OSMQuery for ArcGIS/ArcMap and would like to add an info aboutdonations to Overpass-turbo and OSM on my readme.-...

**Comment by tyrasd** [comment]
Hi! Thanks for the request, but I'm currently not accepting donations for overpass-turbo.

I personally have only very modest costs for running overpass-turbo, since it by itself is a relatively lightweight web application with only small server side component. The heavy "data crunching" is done by various overpass-api servers that are maintained and financed by different entities:

* overpass-api.de (main instance) – maintained by @drolbr and financed by https://www.fossgis.de/ 
* overpass.openstreetmap.fr – maintained and financed by the OSM Foundation local chapter "OpenStreetMap France"
* overpass.kumi.systems – maintained and financed by @kumitterer

(see also https://wiki.openstreetmap.org/wiki/Overpass_API#Public_Overpass_API_instances)

If you want to promote possibilities where people can donate to OSM, I would suggest pointing them to the OSMF in general: https://wiki.openstreetmap.org/wiki/Donations
